# Generated by Django 5.2 on 2025-05-31 10:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtest',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_category', to='hospapp.testcategory'),
        ),
    ]
