# Generated by Django 5.2 on 2025-05-28 18:52

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtest',
            name='date_recorded',
        ),
        migrations.AddField(
            model_name='labtest',
            name='date_performed',
            field=models.DateTimeField(default=datetime.time(19, 52, 0, 824056)),
        ),
        migrations.AddField(
            model_name='labtest',
            name='normal_range',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='labtest',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labtest',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_tests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labtest',
            name='result_value',
            field=models.TextField(default='positive'),
        ),
        migrations.AddField(
            model_name='labtest',
            name='test_category',
            field=models.CharField(default='empty', max_length=100),
        ),
        migrations.AddField(
            model_name='labtest',
            name='test_selection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_results', to='hospapp.testselection'),
        ),
        migrations.AddField(
            model_name='testrequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testrequest',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='testselection',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_tests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='test_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='testselection',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_selections', to='hospapp.patient'),
        ),
        migrations.AlterField(
            model_name='testselection',
            name='submitted_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
