# Generated by Django 5.2 on 2025-06-09 19:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('doctor_name', models.CharField(max_length=100)),
                ('labtech_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='labtest',
            name='doctor_comments',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
