# Generated by Django 5.2 on 2025-06-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('account', 'Account'), ('hms_admin', 'Administrator'), ('doctor', 'Doctor'), ('hr', 'HR'), ('lab', 'Lab Technician'), ('nurse', 'Nurse'), ('pharmacy', 'Pharmacy'), ('receptionist', 'Receptionist')], max_length=20),
        ),
    ]
