# Generated by Django 5.2 on 2025-06-24 12:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='admitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions_admitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='admission',
            name='discharged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions_discharged', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='admission',
            name='doctor_assigned',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions_doctor', to=settings.AUTH_USER_MODEL),
        ),
    ]
