# Generated by Django 5.2 on 2025-06-01 23:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='date_recorded',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='labtest',
            name='date_performed',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
