# Generated by Django 5.2 on 2025-06-09 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labresultfile',
            name='labtest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hospapp.labtest'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='next_of_kin_relationship',
            field=models.CharField(blank=True, choices=[('Spouse', 'Spouse'), ('Father', 'Father'), ('Mother', 'Mother'), ('Son', 'Son'), ('Daughter', 'Daughter'), ('Brother', 'Brother'), ('Sister', 'Sister'), ('Guardian', 'Guardian'), ('Friend', 'Friend'), ('Other', 'Other')], default='Ade', max_length=20, null=True),
        ),
    ]
