# Generated by Django 5.2 on 2025-05-28 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='labtest',
            old_name='date_recorded',
            new_name='date_performed',
        ),
        migrations.AddField(
            model_name='labtest',
            name='normal_range',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='labtest',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='labtest',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_tests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labtest',
            name='result_value',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labtest',
            name='test_category',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='labtest',
            name='test_selection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_results', to='hospapp.testselection'),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_tests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='test_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='testselection',
            name='patient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_selections', to='hospapp.patient'),
        ),
    ]
