# Generated by Django 5.2 on 2025-05-30 14:46

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_date', models.DateField()),
                ('patient_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='labtest',
            name='date_performed',
            field=models.DateTimeField(default=datetime.time(15, 46, 45, 496863)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='hospapp.patientbill'),
        ),
    ]
