# Generated by Django 5.2 on 2025-05-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testselection',
            name='test_name',
            field=models.BooleanField(default=False),
        ),
    ]
