# Generated by Django 5.2 on 2025-06-01 23:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0002_labtest_date_recorded_alter_labtest_date_performed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtest',
            name='date_performed',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='date_recorded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='test_type',
            field=models.CharField(default='typeoftest', max_length=100),
        ),
    ]
