# Generated by Django 5.2 on 2025-05-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0002_alter_testselection_test_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='testselection',
            name='testcompleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='testselection',
            name='test_name',
            field=models.CharField(max_length=100),
        ),
    ]
