# Generated by Django 5.2 on 2025-05-30 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0002_patientadmission_alter_labtest_date_performed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtest',
            name='date_performed',
            field=models.DateTimeField(default=datetime.time(18, 2, 35, 450483)),
        ),
    ]
