# Generated by Django 5.2 on 2025-05-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0002_rename_date_recorded_labtest_date_performed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testrequest',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testrequest',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='testselection',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
