# Generated by Django 5.2 on 2025-05-30 22:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0002_alter_labtest_date_performed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtest',
            name='date_performed',
            field=models.DateTimeField(default=datetime.time(23, 45, 0, 469158)),
        ),
    ]
