# Generated by Django 5.2 on 2025-05-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0002_patient_first_time_patient_id_number_patient_id_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(),
        ),
    ]
