# Generated by Django 5.2 on 2025-05-29 06:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0002_remove_labtest_date_recorded_labtest_date_performed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtest',
            name='date_performed',
            field=models.DateTimeField(default=datetime.time(7, 58, 41, 427425)),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('receptionist', 'Receptionist'), ('nurse', 'Nurse'), ('doctor', 'Doctor'), ('lab', 'Lab Technician'), ('admin', 'Administrator'), ('pharmacy', 'Pharmacy'), ('hr', 'HR'), ('account', 'Account')], max_length=20),
        ),
    ]
