# Generated by Django 5.2 on 2025-06-24 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0002_alter_admission_admitted_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='admission_reason',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
