# Generated by Django 5.2 on 2025-06-10 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0002_doctorcomments_labtest_doctor_comments'),
        ('hospapp', '0003_alter_staff_role'),
    ]

    operations = [
    ]
