# Generated by Django 5.2 on 2025-06-05 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0003_alter_labtest_performed_by_alter_labtest_recorded_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='testcompleted',
            field=models.BooleanField(default=0),
        ),
    ]
