# Generated by Django 5.2 on 2025-05-27 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0003_testselection_testcompleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testselection',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
