# Generated by Django 5.2 on 2025-06-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0003_admission_admission_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='admission_reason',
            field=models.TextField(max_length=254, null=True),
        ),
    ]
