# Generated by Django 5.2 on 2025-05-13 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0003_alter_patient_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='last_name',
        ),
    ]
