# Generated by Django 5.2 on 2025-05-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0004_remove_patient_first_name_remove_patient_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='id_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='marital_status',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nationality',
            field=models.CharField(max_length=50),
        ),
    ]
