# Generated by Django 5.2 on 2025-06-24 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0004_alter_admission_admission_reason'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='handoverlog',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handovers_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='handoverlog',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handovers_made', to=settings.AUTH_USER_MODEL),
        ),
    ]
