# Generated by Django 5.2 on 2025-05-28 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0004_referral_created_at_alter_testselection_submitted_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='testselection',
            name='submitted_on',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
