# Generated by Django 5.2 on 2025-06-10 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0004_merge_20250610_0738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='bed',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='bed',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='ward',
        ),
        migrations.RemoveField(
            model_name='admission',
            name='ward',
        ),
        migrations.DeleteModel(
            name='Bed',
        ),
        migrations.DeleteModel(
            name='Ward',
        ),
    ]
