# Generated by Django 5.2 on 2025-05-22 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0005_alter_appointment_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labtest',
            name='blood_type',
        ),
        migrations.RemoveField(
            model_name='labtest',
            name='hormone',
        ),
        migrations.RemoveField(
            model_name='labtest',
            name='hormone_level',
        ),
        migrations.RemoveField(
            model_name='labtest',
            name='infection_result',
        ),
        migrations.RemoveField(
            model_name='labtest',
            name='infection_type',
        ),
        migrations.RemoveField(
            model_name='labtest',
            name='motility',
        ),
        migrations.RemoveField(
            model_name='labtest',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='labtest',
            name='pregnancy_result',
        ),
        migrations.RemoveField(
            model_name='labtest',
            name='sperm_count',
        ),
    ]
