# Generated by Django 5.2 on 2025-05-28 17:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0005_remove_referral_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testselection',
            name='submitted_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
