# Generated by Django 5.2 on 2025-06-11 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0005_remove_patient_bed_remove_admission_bed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labresultfile',
            name='labtest',
        ),
        migrations.AddField(
            model_name='labtest',
            name='labresulttestid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
