# Generated by Django 5.2 on 2025-05-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0005_alter_patient_id_type_alter_patient_marital_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='first_time',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
