# Generated by Django 5.2 on 2025-05-28 17:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0006_referral_created_at_alter_testselection_submitted_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
