# Generated by Django 5.2 on 2025-06-12 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0006_remove_labresultfile_labtest_labtest_labresulttestid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MedicalRecord',
        ),
    ]
