# Generated by Django 5.2 on 2025-06-24 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0006_alter_nursingnote_nurse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nursingnote',
            name='nurse',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
