# Generated by Django 5.2 on 2025-05-22 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0006_remove_labtest_blood_type_remove_labtest_hormone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=255)),
                ('lab_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='hospapp.labtest')),
            ],
        ),
    ]
