# Generated by Django 5.2 on 2025-05-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0007_rename_bed_number_bed_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='assigned_by',
            field=models.CharField(default=11),
            preserve_default=False,
        ),
    ]
