# Generated by Django 5.2 on 2025-06-13 06:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0007_delete_medicalrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='test_request_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
