# Generated by Django 5.2 on 2025-05-28 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0007_alter_referral_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='created_at',
        ),
    ]
