# Generated by Django 5.2 on 2025-06-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0008_labtest_test_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
