# Generated by Django 5.2 on 2025-05-15 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0008_admission_assigned_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admission',
            old_name='assigned_by',
            new_name='admitted_by',
        ),
    ]
