# Generated by Django 5.2 on 2025-06-24 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0008_alter_nursingnote_nurse'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='priority',
            field=models.CharField(blank=True, null=True),
        ),
    ]
