# Generated by Django 5.2 on 2025-05-24 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0009_testselection'),
    ]

    operations = [
        migrations.AddField(
            model_name='testselection',
            name='patient_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hospapp.patient'),
        ),
    ]
