# Generated by Django 5.2 on 2025-05-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0009_rename_assigned_by_admission_admitted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='discharged_by',
            field=models.CharField(default=1),
            preserve_default=False,
        ),
    ]
