# Generated by Django 5.2.3 on 2025-07-01 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0009_referral_priority'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorcomments',
            name='doctor_name',
        ),
        migrations.AddField(
            model_name='doctorcomments',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_made_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
