# Generated by Django 5.2 on 2025-06-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0009_alter_consultation_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
