# Generated by Django 5.2 on 2025-05-15 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0010_admission_discharged_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='admitted_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='discharged_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
