# Generated by Django 5.2 on 2025-06-18 15:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0010_alter_consultation_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staff',
            options={'permissions': [('can_edit_staff_profiles', "Can edit any staff user's profile details (username, email, names, role, phone)"), ('can_change_staff_status', 'Can activate/deactivate staff user accounts'), ('can_view_staff_list', 'Can view the list of all staff users in the admin area'), ('can_reset_staff_password', 'Can reset staff user passwords')]},
        ),
        migrations.AddField(
            model_name='referral',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
