# Generated by Django 5.2 on 2025-07-06 22:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0010_remove_doctorcomments_doctor_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorcomments',
            name='doctor',
        ),
        migrations.AddField(
            model_name='doctorcomments',
            name='doctor_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_made_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
