# Generated by Django 5.2 on 2025-05-24 20:38

import datetime
import hospapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0010_testselection_patient_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='testselection',
            name='submitted_on',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='testselection',
            name='time',
            field=models.TimeField(default=hospapp.models.TestSelection.get_current_time),
        ),
    ]
