# Generated by Django 5.2 on 2025-05-27 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0002_alter_attendance_date'),
        ('hospapp', '0011_testselection_submitted_on_testselection_time'),
    ]

    operations = [
    ]
