# Generated by Django 5.2 on 2025-07-08 20:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0011_remove_doctorcomments_doctor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IVFPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('Decription', models.CharField(max_length=255)),
                ('price', models.FloatField(default=0.0, max_length=255)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='doctorcomments',
            name='doctor_name',
        ),
        migrations.AddField(
            model_name='doctorcomments',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_made_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='IVFRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=255)),
                ('doctor_comments', models.TextField(blank=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('ivf_package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospapp.ivfpackage')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospapp.patient')),
                ('treatment_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospapp.treatmentlocation')),
            ],
        ),
    ]
