# Generated by Django 5.2 on 2025-05-15 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0012_vitals'),
    ]

    operations = [
        migrations.AddField(
            model_name='vitals',
            name='bmi',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
