# Generated by Django 5.2 on 2025-07-08 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0012_ivfpackage_treatmentlocation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ivfrecord',
            name='status',
            field=models.CharField(default='open', max_length=255),
        ),
    ]
