# Generated by Django 5.2.3 on 2025-07-10 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0013_ivfrecord_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IVFProgressUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', 'Open'), ('pending', 'Pending'), ('in_progress', 'In Progress'), ('stimulation', 'Stimulation Phase'), ('egg_retrieval', 'Egg Retrieval'), ('fertilization', 'Fertilization'), ('embryo_transfer', 'Embryo Transfer'), ('luteal_phase', 'Luteal Phase'), ('pregnancy_test', 'Pregnancy Test'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=50)),
                ('comments', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ivf_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to='hospapp.ivfrecord')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'IVF Progress Updates',
                'ordering': ['timestamp'],
            },
        ),
    ]
