# Generated by Django 5.2 on 2025-05-15 19:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0013_vitals_bmi'),
    ]

    operations = [
        migrations.CreateModel(
            name='NursingNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('note_type', models.CharField(choices=[('observation', 'Observation'), ('medication', 'Medication Administered'), ('response', 'Patient Response'), ('care_plan', 'Care Plan Update'), ('other', 'Other')], max_length=50)),
                ('nurse', models.CharField(max_length=100)),
                ('patient_status', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField()),
                ('follow_up', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nursing_notes', to='hospapp.patient')),
            ],
        ),
    ]
