# Generated by Django 5.2.3 on 2025-07-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0014_ivfprogressupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ivfrecord',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('pending', 'Pending'), ('in_progress', 'In Progress'), ('stimulation', 'Stimulation Phase'), ('egg_retrieval', 'Egg Retrieval'), ('fertilization', 'Fertilization'), ('embryo_transfer', 'Embryo Transfer'), ('luteal_phase', 'Luteal Phase'), ('pregnancy_test', 'Pregnancy Test'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=255),
        ),
    ]
