# Generated by Django 5.2 on 2025-05-16 22:14

import datetime
import hospapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0014_nursingnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='admitted_on',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='admission',
            name='time',
            field=models.TimeField(default=hospapp.models.Admission.get_current_time),
        ),
    ]
