# Generated by Django 5.2.3 on 2025-07-16 15:00

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0017_alter_attendance_options_alter_attendance_staff_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='shiftassignment',
            options={},
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='check_in_time',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='check_out_time',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='recorded_at',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='description',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='shiftassignment',
            name='assigned_at',
        ),
        migrations.RemoveField(
            model_name='shiftassignment',
            name='assigned_by',
        ),
        migrations.RemoveField(
            model_name='shiftassignment',
            name='notes',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Absent', 'Absent'), ('On Leave', 'On Leave'), ('Present', 'Present')], max_length=10),
        ),
        migrations.AlterField(
            model_name='shift',
            name='name',
            field=models.CharField(choices=[('Afternoon', 'Afternoon'), ('Morning', 'Morning'), ('Night', 'Night')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='shiftassignment',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
