# Generated by Django 5.2 on 2025-05-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0017_prescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='symptoms',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
