# Generated by Django 5.2.3 on 2025-07-18 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0018_alter_attendance_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shiftassignment',
            name='shift',
            field=models.CharField(choices=[('Afternoon', 'Afternoon'), ('Morning', 'Morning'), ('Night', 'Night')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Shift',
        ),
    ]
