# Generated by Django 5.2 on 2025-07-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0019_alter_shiftassignment_shift_delete_shift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='scheduled_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
