# Generated by Django 5.2 on 2025-05-19 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0020_careplan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_type', models.CharField(choices=[('semen', 'Semen Analysis'), ('blood', 'Blood Screening'), ('hormone', 'Hormonal Assay'), ('pregnancy', 'Pregnancy Test'), ('infection', 'Infection Screening')], max_length=20)),
                ('date_recorded', models.DateTimeField(auto_now_add=True)),
                ('sperm_count', models.FloatField(blank=True, null=True)),
                ('motility', models.FloatField(blank=True, null=True)),
                ('blood_type', models.CharField(blank=True, max_length=5, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('hormone', models.CharField(blank=True, max_length=100, null=True)),
                ('hormone_level', models.FloatField(blank=True, null=True)),
                ('pregnancy_result', models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative')], max_length=10, null=True)),
                ('infection_type', models.CharField(blank=True, max_length=100, null=True)),
                ('infection_result', models.CharField(blank=True, choices=[('positive', 'Positive'), ('negative', 'Negative')], max_length=10, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospapp.patient')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
