# Generated by Django 5.2 on 2025-05-19 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospapp', '0021_labtest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtest',
            name='test_type',
            field=models.CharField(choices=[('semen', 'Semen Analysis'), ('blood', 'Blood Screening'), ('hormone', 'Hormonal Assay'), ('pregnancy', 'Pregnancy Test'), ('infection', 'Infection Screening'), ('combined', 'Combined Tests')], max_length=20),
        ),
    ]
